import os
import sys
import pandas as pd

#
# setup the env for each exacution
# this allows you to specify a file that contains all the modules you want to have loaded
# for you pipeline.
# the file should be called modules.cfg and should exist in the same locaiton as the snakemake file
#
SNAKEMAKE_DIR = os.path.dirname(workflow.snakefile)
shell.executable("/bin/bash")
shell.prefix("source %s/modules.cfg; set -eo pipefail; " % SNAKEMAKE_DIR)



#
# the config file is where you will have the input to your program, 
# so in your case a reference genome and a fastq file
# you can access things in your config file in this way 
# config["the name of the vraible you want"]
#
configfile: "config.yml"


#
# an all rule always is the first rule in a file
# bscially it should have as input the final file you want generated by 
# this porgram
#
rule all:
	input:




#
# example python rule 
#

